'use strict';
/* ERZEUGT von tools/grafikmanifest.mjs — nicht von Hand aendern.
 * Nach dem Anlegen eines neuen Moduls einmal laufen lassen. */
window.GRAFIK_MODULE = [
 "grafik/glsl.js",
 "grafik/licht.js",
 "grafik/himmel.js",
 "grafik/nebel.js",
 "grafik/boden.js",
 "grafik/schatten.js",
 "grafik/rampe.js",
 "grafik/kontur.js",
 "grafik/wasser.js",
 "grafik/gras.js",
 "grafik/karte.js",
 "grafik/props/baum.js",
 "grafik/props/baumstumpf.js",
 "grafik/props/blume.js",
 "grafik/props/busch.js",
 "grafik/props/fern.js",
 "grafik/props/gras-buschel.js",
 "grafik/props/pilz.js",
 "grafik/props/ruine.js",
 "grafik/props/stein.js",
 "grafik/props/weg.js",
 "grafik/gel.js",
 "grafik/schleim/farbe.js",
 "grafik/schleim/glanz.js",
 "grafik/schleim/huelle.js",
 "grafik/schleim/innen.js",
 "grafik/schleim/kontakt.js",
 "grafik/schleim/rand.js",
 "grafik/schleim/reaktion.js",
 "grafik/schleim/schattenform.js",
 "grafik/schleim/spur.js",
 "grafik/schleim/wachstum.js",
 "grafik/post.js",
 "grafik/gesicht.js",
 "grafik/renderer2.js"
];
