import * as THREE from './node_modules/three/build/three.module.js';

const canvas=document.querySelector('#game');
const ui={target:document.querySelector('#target'),targetName:document.querySelector('#targetName'),targetState:document.querySelector('#targetState'),targetHp:document.querySelector('#targetHp'),targetHint:document.querySelector('#targetHint'),playerHp:document.querySelector('#playerHp'),playerEnergy:document.querySelector('#playerEnergy'),playerState:document.querySelector('#playerState'),toast:document.querySelector('#toast'),coords:document.querySelector('#coords')};
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight,false);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x79cffa);scene.fog=new THREE.Fog(0x96d9d2,30,72);
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,140);
const raycaster=new THREE.Raycaster(),mouse=new THREE.Vector2(),clock=new THREE.Clock(),loader=new THREE.TextureLoader();
const keys=new Set();let yaw=.72,pitch=.43,distance=14,drag=false,lastX=0,lastY=0,target=null,enemies=[],toastTimer=0;
const worldUp=new THREE.Vector3(0,1,0),cameraForward=new THREE.Vector3(),cameraRight=new THREE.Vector3();

scene.add(new THREE.HemisphereLight(0xdff8ff,0x57913e,2.2));const sun=new THREE.DirectionalLight(0xfff2c9,2.6);sun.position.set(-12,24,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-28;sun.shadow.camera.right=28;sun.shadow.camera.top=28;sun.shadow.camera.bottom=-28;scene.add(sun);

const animationManifest=await fetch('assets/animations/manifest.json').then(response=>response.json());
const texturePaths={grass:'assets/anime-grass-tile.png'};
for(const [kind,actions] of Object.entries(animationManifest))if(typeof actions==='object')for(const [action,definition] of Object.entries(actions))texturePaths[`${kind}:${action}`]=definition.src;
const textures={};
await Promise.all(Object.entries(texturePaths).map(async([name,path])=>{const t=await loader.loadAsync(path);t.colorSpace=THREE.SRGBColorSpace;t.magFilter=THREE.LinearFilter;t.minFilter=THREE.LinearMipmapLinearFilter;textures[name]=t;}));

const grass=textures.grass;grass.wrapS=grass.wrapT=THREE.RepeatWrapping;grass.repeat.set(10,10);grass.anisotropy=renderer.capabilities.getMaxAnisotropy();
const ground=new THREE.Mesh(new THREE.PlaneGeometry(80,80),new THREE.MeshStandardMaterial({map:grass,color:0xcaff9b,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;ground.name='ground';scene.add(ground);

function addScenery(){const trunkMat=new THREE.MeshToonMaterial({color:0x745029}),leafMats=[0x53ae42,0x79c84c,0x3f963d].map(c=>new THREE.MeshToonMaterial({color:c}));for(let i=0;i<26;i++){const a=i/26*Math.PI*2,r=31+Math.sin(i*2.7)*4,x=Math.cos(a)*r,z=Math.sin(a)*r;const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.35,.55,3.6,7),trunkMat);trunk.position.set(x,1.8,z);trunk.castShadow=true;const crown=new THREE.Mesh(new THREE.IcosahedronGeometry(2.2+(i%3)*.3,1),leafMats[i%3]);crown.position.set(x,4.6,z);crown.scale.y=1.2;crown.castShadow=true;scene.add(trunk,crown);}const rockMat=new THREE.MeshToonMaterial({color:0x91a992});for(let i=0;i<18;i++){const a=i/18*Math.PI*2+.2,r=25+Math.sin(i*4)*3,rock=new THREE.Mesh(new THREE.DodecahedronGeometry(1+(i%4)*.22,0),rockMat);rock.position.set(Math.cos(a)*r,.55,Math.sin(a)*r);rock.scale.y=.65;rock.rotation.y=a;rock.castShadow=true;rock.receiveShadow=true;scene.add(rock);}}
addScenery();

const marker=new THREE.Mesh(new THREE.RingGeometry(.7,.82,48),new THREE.MeshBasicMaterial({color:0xb7ffcf,transparent:true,opacity:.8,side:THREE.DoubleSide}));marker.rotation.x=-Math.PI/2;marker.position.y=.035;marker.visible=false;scene.add(marker);
const combatRing=new THREE.Mesh(new THREE.RingGeometry(1.98,2.08,64),new THREE.MeshBasicMaterial({color:0xffe36a,transparent:true,opacity:.72,side:THREE.DoubleSide}));combatRing.rotation.x=-Math.PI/2;combatRing.position.y=.04;combatRing.visible=false;scene.add(combatRing);

function textureFor(kind){const t=textures[kind].clone();t.wrapS=t.wrapT=THREE.ClampToEdgeWrapping;t.generateMipmaps=false;t.minFilter=THREE.LinearFilter;t.magFilter=THREE.LinearFilter;t.needsUpdate=true;return t;}
const directionNames=['back','back-right','right','front-right','front','front-left','left','back-left'];
function entity(kind,name,x,z){const isPlayer=kind==='slime',animation=isPlayer?'slime:idle-back':`${kind}:idle-right`,map=textureFor(animation),mat=new THREE.SpriteMaterial({map,transparent:true,depthTest:true,depthWrite:false,alphaTest:.045}),sprite=new THREE.Sprite(mat);sprite.center.set(.5,0);const shadow=new THREE.Mesh(new THREE.CircleGeometry(isPlayer ? .72 : .64,32),new THREE.MeshBasicMaterial({color:0x173b25,transparent:true,opacity:.2,depthWrite:false}));shadow.rotation.x=-Math.PI/2;shadow.position.y=.025;scene.add(shadow,sprite);const e={kind,name,x,z,spawnX:x,spawnZ:z,vx:0,vz:0,face:0,hp:isPlayer?100:(kind==='wolf'?70:90),maxHp:isPlayer?100:(kind==='wolf'?70:90),energy:100,state:'idle',stateT:0,duration:0,frameRate:12,size:isPlayer?2.65:(kind==='wolf'?2.6:2.5),sprite,shadow,map,animation,moveTarget:null,combatTarget:null,combatDirection:null,combatMirror:false,queuedAttack:false,attackCd:0,invuln:0,aggro:false,dead:false,respawning:false};sprite.userData.entity=e;syncSprite(e);return e;}
const player=entity('slime','Azur-Schleim',0,0);
function spawnEnemies(){for(const e of enemies)scene.remove(e.sprite,e.shadow);enemies=[entity('wolf','Nebelwolf',-9,-7),entity('boar','Dornen-Eber',10,-5),entity('wolf','Silberwolf',9,9),entity('boar','Rotborsten-Eber',-10,8)];}
spawnEnemies();

function setState(e,state,duration=0){if(e.state===state&&(!duration||e.duration===duration))return;e.state=state;e.stateT=0;e.duration=duration;}
function facingRow(e){if(e.kind==='slime'&&e.combatDirection!==null)return e.combatDirection;camera.getWorldDirection(cameraForward);cameraForward.y=0;cameraForward.normalize();cameraRight.crossVectors(cameraForward,worldUp).normalize();const fx=Math.sin(e.face),fz=Math.cos(e.face),side=fx*cameraRight.x+fz*cameraRight.z,depth=fx*cameraForward.x+fz*cameraForward.z;return(Math.round(Math.atan2(side,-depth)/(Math.PI/4))+8)%8;}
function enemySide(e){camera.getWorldDirection(cameraForward);cameraForward.y=0;cameraForward.normalize();cameraRight.crossVectors(cameraForward,worldUp).normalize();const side=Math.sin(e.face)*cameraRight.x+Math.cos(e.face)*cameraRight.z;return side<0?'left':'right';}
function setFrame(e){let action;if(e.kind==='slime')action=['idle','move','attack'].includes(e.state)?`${e.state}-${directionNames[facingRow(e)]}`:e.state;else action=`${e.state}-${enemySide(e)}`;const animation=`${e.kind}:${action}`,definition=animationManifest[e.kind][action],cols=definition.cols,loop=e.state==='idle'||e.state==='move',fps=e.state==='idle'?(e.kind==='slime'?0:0.8):9,frame=loop?(fps?Math.floor(e.stateT*fps)%cols:0):Math.min(cols-1,Math.floor(Math.min(.999,e.stateT/Math.max(.001,e.duration))*cols));if(e.animation!==animation){e.animation=animation;e.map.dispose();e.map=textureFor(animation);e.sprite.material.map=e.map;e.sprite.material.needsUpdate=true;}const img=textures[animation].image,cellU=1/cols,padU=2/img.width,padV=2/img.height;e.map.repeat.set(cellU-padU*2,1-padV*2);e.map.offset.set(frame*cellU+padU,padV);const aspect=definition.cellWidth/definition.cellHeight,breath=e.state==='idle'?Math.sin(e.stateT*.68):0;e.sprite.scale.set(e.size*aspect*(1+breath*.009),e.size*(1-breath*.006),1);e.sprite.position.y=.018-e.size*definition.padding/definition.cellHeight;}
function syncSprite(e){e.sprite.position.x=e.x;e.sprite.position.z=e.z;e.shadow.position.x=e.x;e.shadow.position.z=e.z;setFrame(e);e.sprite.visible=e.shadow.visible=!e.dead;}

function toast(text,color='#fff'){ui.toast.textContent=text;ui.toast.style.color=color;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),900);}
function updateCamera(){const cp=Math.cos(pitch);camera.position.set(player.x+Math.sin(yaw)*cp*distance,1.15+Math.sin(pitch)*distance,player.z+Math.cos(yaw)*cp*distance);camera.lookAt(player.x,1.05,player.z);}
function movePlayer(dx,dz,dt){if(!['idle','move'].includes(player.state))return;const speed=5.2;player.vx+=(dx*speed-player.vx)*Math.min(1,dt*9);player.vz+=(dz*speed-player.vz)*Math.min(1,dt*9);player.face=Math.atan2(dx,dz);setState(player,'move');}
function stopPlayer(dt){player.vx*=Math.exp(-12*dt);player.vz*=Math.exp(-12*dt);if(player.state==='move')setState(player,'idle');}
function updatePlayer(dt){player.attackCd=Math.max(0,player.attackCd-dt);player.invuln=Math.max(0,player.invuln-dt);player.energy=Math.min(100,player.energy+18*dt);if(player.combatTarget&&(player.combatTarget.dead||player.combatTarget.hp<=0)){player.combatTarget=null;player.combatDirection=null;player.combatMirror=false;player.queuedAttack=false;}const c=player.combatTarget;if(c){let dx=c.x-player.x,dz=c.z-player.z,d=Math.hypot(dx,dz)||1;player.face=Math.atan2(dx,dz);combatRing.visible=true;combatRing.position.set(c.x,.04,c.z);if(['idle','move'].includes(player.state)){if(d>2.18)movePlayer(dx/d,dz/d,dt);else if(d<1.88)movePlayer(-dx/d,-dz/d,dt);else{player.vx=player.vz=0;if(player.state==='move')setState(player,'idle');if(player.queuedAttack)performAttack(c);}}else{player.vx=player.vz=0;if(d<1.88){player.x=c.x-dx/d*2.02;player.z=c.z-dz/d*2.02;}}}else{combatRing.visible=false;let ix=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),iz=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0);if(ix||iz){camera.getWorldDirection(cameraForward);cameraForward.y=0;cameraForward.normalize();cameraRight.crossVectors(cameraForward,worldUp).normalize();const dir=new THREE.Vector3().addScaledVector(cameraRight,ix).addScaledVector(cameraForward,-iz).normalize();movePlayer(dir.x,dir.z,dt);player.moveTarget=null;marker.visible=false;}else if(player.moveTarget&&['idle','move'].includes(player.state)){const dx=player.moveTarget.x-player.x,dz=player.moveTarget.z-player.z,d=Math.hypot(dx,dz);if(d>.2)movePlayer(dx/d,dz/d,dt);else{player.moveTarget=null;marker.visible=false;stopPlayer(dt);}}else stopPlayer(dt);}player.x=THREE.MathUtils.clamp(player.x+player.vx*dt,-28,28);player.z=THREE.MathUtils.clamp(player.z+player.vz*dt,-28,28);advance(player,dt);syncSprite(player);}
function advance(e,dt){e.stateT+=dt;if(e.duration&&e.stateT>=e.duration){if(e.state==='death'){e.dead=true;e.sprite.visible=e.shadow.visible=false;if(e!==player&&!e.respawning){e.respawning=true;if(target===e)target=null;setTimeout(()=>respawnEnemy(e),4000);}return;}e.duration=0;setState(e,'idle');}}
function respawnEnemy(e){e.x=e.spawnX+(Math.random()-.5)*2;e.z=e.spawnZ+(Math.random()-.5)*2;e.hp=e.maxHp;e.vx=e.vz=0;e.dead=false;e.respawning=false;e.aggro=false;e.attackCd=1;e.duration=0;e.combatDirection=null;setState(e,'idle');syncSprite(e);toast(`${e.name.toUpperCase()} IST ZURÜCK`,'#baff91');}
function updateEnemy(e,dt){if(e.dead)return;advance(e,dt);e.attackCd-=dt;if(['idle','move'].includes(e.state)&&e.aggro){const dx=player.x-e.x,dz=player.z-e.z,d=Math.hypot(dx,dz)||1;e.face=Math.atan2(dx,dz);if(d>2.08){setState(e,'move');const s=e.kind==='wolf'?2.15:1.7;e.x+=dx/d*s*dt;e.z+=dz/d*s*dt;}else if(e.attackCd<=0){setState(e,'attack',.75);e.attackCd=e.kind==='wolf'?1.8:2.2;setTimeout(()=>{if(e.dead)return;if(Math.hypot(player.x-e.x,player.z-e.z)<2.5&&player.invuln<=0){player.hp=Math.max(0,player.hp-(e.kind==='wolf'?9:13));player.invuln=.5;setState(player,player.hp?'hit':'death',player.hp?.55:1.2);}},330);}else setState(e,'idle');}syncSprite(e);}
function attack(){if(player.attackCd>0||player.energy<20)return;const e=target&&!target.dead?target:nearestEnemy();if(!e)return;target=e;e.aggro=true;player.face=Math.atan2(e.x-player.x,e.z-player.z);player.combatTarget=e;if(player.combatDirection===null){player.combatDirection=facingRow(player);camera.getWorldDirection(cameraForward);cameraForward.y=0;cameraForward.normalize();cameraRight.crossVectors(cameraForward,worldUp).normalize();player.combatMirror=((e.x-player.x)*cameraRight.x+(e.z-player.z)*cameraRight.z)<0;}player.queuedAttack=true;player.moveTarget=null;marker.visible=false;toast('ZIEL-LOCK · RICHTUNG FIXIERT','#ffe47a');}
function performAttack(e){if(!player.queuedAttack||player.attackCd>0)return;player.queuedAttack=false;player.energy-=20;player.attackCd=.78;setState(player,'attack',.78);setTimeout(()=>{if(e.dead)return;e.hp=Math.max(0,e.hp-24);setState(e,e.hp?'hit':'death',e.hp?.62:1.25);toast(e.hp?'24 SCHADEN':'BESIEGT',e.hp?'#fff':'#ffce66');},320);}
function eat(){const e=target&&!target.dead?target:nearestEnemy();if(!e)return;const dx=e.x-player.x,dz=e.z-player.z,d=Math.hypot(dx,dz);if(d>2.35){player.combatTarget=e;toast('ERST AUF FRESSDISTANZ','#ffd277');return;}if(e.hp/e.maxHp>.35){toast('ERST AUF 35 % SCHWÄCHEN','#ff8a78');return;}player.face=Math.atan2(dx,dz);setState(player,'eat',1.25);setTimeout(()=>{e.hp=0;setState(e,'death',1.15);player.combatTarget=null;player.combatDirection=null;player.hp=Math.min(100,player.hp+22);toast('VERSCHLUNGEN!','#75f5cf');},720);}
function nearestEnemy(){return enemies.filter(e=>!e.dead).sort((a,b)=>Math.hypot(a.x-player.x,a.z-player.z)-Math.hypot(b.x-player.x,b.z-player.z))[0];}
function reset(){Object.assign(player,{x:0,z:0,vx:0,vz:0,hp:100,energy:100,state:'idle',stateT:0,duration:0,moveTarget:null,combatTarget:null,combatDirection:null,combatMirror:false,queuedAttack:false,dead:false});spawnEnemies();target=null;marker.visible=false;combatRing.visible=false;syncSprite(player);}
function updateUI(){ui.playerHp.style.width=player.hp+'%';ui.playerEnergy.style.width=player.energy+'%';ui.playerState.textContent=player.state.toUpperCase();ui.coords.textContent=`POSITION ${player.x.toFixed(1)} / ${player.z.toFixed(1)}`;if(target&&!target.dead){const d=Math.hypot(target.x-player.x,target.z-player.z);ui.target.classList.remove('hidden');ui.targetName.textContent=target.name;ui.targetHp.style.width=target.hp/target.maxHp*100+'%';ui.targetState.textContent=target.state.toUpperCase();ui.targetHint.textContent=target.hp/target.maxHp<=.35?'FRESSBAR – E DRÜCKEN':`${Math.ceil(target.hp)} / ${target.maxHp} HP · DISTANZ ${d.toFixed(1)}`;}else ui.target.classList.add('hidden');}

canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{canvas.focus();if(e.button===2){drag=true;lastX=e.clientX;lastY=e.clientY;canvas.setPointerCapture(e.pointerId);return;}mouse.set(e.clientX/innerWidth*2-1,-e.clientY/innerHeight*2+1);raycaster.setFromCamera(mouse,camera);const sprites=enemies.filter(x=>!x.dead).map(x=>x.sprite),hits=raycaster.intersectObjects(sprites,false);if(hits.length){target=hits[0].object.userData.entity;toast(target.name.toUpperCase(),'#ffda87');}else{const hit=raycaster.intersectObject(ground,false)[0];if(hit){player.combatTarget=null;player.combatDirection=null;player.combatMirror=false;player.queuedAttack=false;target=null;player.moveTarget={x:hit.point.x,z:hit.point.z};marker.position.set(hit.point.x,.04,hit.point.z);marker.visible=true;}}});
canvas.addEventListener('pointermove',e=>{if(!drag)return;yaw-=(e.clientX-lastX)*.006;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-lastY)*.005,.12,1.05);lastX=e.clientX;lastY=e.clientY;});canvas.addEventListener('pointerup',e=>{if(e.button===2)drag=false;});canvas.addEventListener('wheel',e=>distance=THREE.MathUtils.clamp(distance+e.deltaY*.012,8,25),{passive:true});
document.addEventListener('keydown',e=>{keys.add(e.code);if(['KeyW','KeyA','KeyS','KeyD','Space'].includes(e.code))e.preventDefault();if(e.repeat)return;if(e.code==='Digit1')attack();if(e.code==='KeyE')eat();if(e.code==='KeyR')reset();});document.addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight,false);});document.querySelector('#toggleHelp').onclick=()=>document.querySelector('#help').classList.toggle('hidden');

function animate(){requestAnimationFrame(animate);const dt=Math.min(.033,clock.getDelta());updatePlayer(dt);for(const e of enemies)updateEnemy(e,dt);updateCamera();updateUI();renderer.render(scene,camera);}
updateCamera();document.body.classList.add('loaded');animate();
