(() => {
  'use strict';
  const canvas=document.querySelector('#game'), ctx=canvas.getContext('2d',{alpha:false});
  const ui={target:document.querySelector('#target'),targetName:document.querySelector('#targetName'),targetState:document.querySelector('#targetState'),targetHp:document.querySelector('#targetHp'),targetHint:document.querySelector('#targetHint'),playerHp:document.querySelector('#playerHp'),playerEnergy:document.querySelector('#playerEnergy'),playerState:document.querySelector('#playerState'),toast:document.querySelector('#toast')};
  const atlases={};
  const atlasDefs={slime:{src:'assets/slime-atlas.png',cols:6,rows:6},directional:{src:'assets/slime-directional-8x12.png',cols:12,rows:16},wolf:{src:'assets/wolf-atlas-12.png',cols:12,rows:5},boar:{src:'assets/boar-atlas-12.png',cols:12,rows:5},meadow:{src:'assets/anime-meadow.png'}};
  const keys=new Set(), pointer={x:0,y:0,drag:false,lastX:0,lastY:0};
  let W=0,H=0,dpr=1,last=performance.now(),target=null,toastTimer=0,gameOver=false;
  const camera={yaw:.72,pitch:.2,dist:14,target:{x:0,y:.8,z:0}};
  const player={kind:'slime',name:'Azur-Schleim',x:0,y:0,z:0,vx:0,vz:0,face:0,hp:100,maxHp:100,energy:100,state:'idle',stateT:0,duration:0,row:0,frameRate:12,size:2.65,moveTarget:null,combatTarget:null,queuedAttack:false,jump:0,jumpV:0,attackCd:0,invuln:0};
  let enemies=[],particles=[];
  const rocks=[];

  function load(){return Promise.all(Object.entries(atlasDefs).map(([k,d])=>new Promise((ok,bad)=>{const i=new Image();i.onload=()=>{atlases[k]=i;ok();};i.onerror=bad;i.src=d.src;})));}
  function reset(){Object.assign(player,{x:0,z:0,vx:0,vz:0,hp:100,energy:100,state:'idle',stateT:0,row:0,moveTarget:null,combatTarget:null,queuedAttack:false,jump:0,jumpV:0});enemies=[makeEnemy('wolf','Nebelwolf',-9,-7),makeEnemy('boar','Dornen-Eber',10,-5),makeEnemy('wolf','Silberwolf',9,9),makeEnemy('boar','Rotborsten-Eber',-10,8)];target=null;particles=[];gameOver=false;canvas.focus();updateUI();}
  function makeEnemy(kind,name,x,z){return{kind,name,x,z,vx:0,vz:0,face:Math.random()*Math.PI*2,mirror:false,aggro:false,hp:kind==='wolf'?70:90,maxHp:kind==='wolf'?70:90,state:'idle',stateT:0,duration:0,row:0,frameRate:12,size:kind==='wolf'?2.6:2.5,attackCd:1+Math.random(),dead:false,screen:null};}
  const stateRows={slime:{idle:0,move:1,attack:2,hit:3,eat:4,death:5},enemy:{idle:0,move:1,attack:2,hit:3,death:4}};
  function setState(o,s,d=0){if(o.state===s&&(!d||o.duration===d))return;o.state=s;o.stateT=0;o.duration=d;o.row=o.kind==='slime'?stateRows.slime[s]:stateRows.enemy[s];}
  function timedState(o,s,d){setState(o,s,d);}
  function toast(text,color='#fff'){ui.toast.textContent=text;ui.toast.style.color=color;ui.toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>ui.toast.classList.remove('show'),900);}
  function resize(){dpr=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*dpr;canvas.height=H*dpr;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(dpr,0,0,dpr,0,0);ctx.imageSmoothingEnabled=true;}
  function basis(){const cp=Math.cos(camera.pitch),sp=Math.sin(camera.pitch),cy=Math.cos(camera.yaw),sy=Math.sin(camera.yaw);const eye={x:camera.target.x+sy*cp*camera.dist,y:camera.target.y+sp*camera.dist,z:camera.target.z+cy*cp*camera.dist};const f=norm({x:camera.target.x-eye.x,y:camera.target.y-eye.y,z:camera.target.z-eye.z});const r=norm({x:f.z,y:0,z:-f.x});const u=cross(f,r);return{eye,f,r,u};}
  function norm(v){const l=Math.hypot(v.x,v.y,v.z)||1;return{x:v.x/l,y:v.y/l,z:v.z/l};} function cross(a,b){return{x:a.y*b.z-a.z*b.y,y:a.z*b.x-a.x*b.z,z:a.x*b.y-a.y*b.x};}
  function project(p,b=basis()){const q={x:p.x-b.eye.x,y:p.y-b.eye.y,z:p.z-b.eye.z},depth=q.x*b.f.x+q.y*b.f.y+q.z*b.f.z;if(depth<.15)return null;const focal=H*.92;return{x:W/2+(q.x*b.r.x+q.y*b.r.y+q.z*b.r.z)*focal/depth,y:H/2-(q.x*b.u.x+q.y*b.u.y+q.z*b.u.z)*focal/depth,depth,scale:focal/depth};}
  function groundFromScreen(sx,sy){const b=basis(),nx=(sx-W/2)/(H*.92),ny=-(sy-H/2)/(H*.92),dir=norm({x:b.f.x+b.r.x*nx+b.u.x*ny,y:b.f.y+b.r.y*nx+b.u.y*ny,z:b.f.z+b.r.z*nx+b.u.z*ny});if(dir.y>=-.001)return null;const t=-b.eye.y/dir.y;return t>0?{x:b.eye.x+dir.x*t,z:b.eye.z+dir.z*t}:null;}
  function drawWorld(b){const meadow=atlases.meadow;if(meadow){const scale=Math.max(W/meadow.width,H/meadow.height),sw=W/scale,sh=H/scale,sx=(meadow.width-sw)/2,sy=Math.max(0,(meadow.height-sh)*.42);ctx.drawImage(meadow,sx,sy,sw,sh,0,0,W,H);}else{ctx.fillStyle='#75bfe0';ctx.fillRect(0,0,W,H);}drawGround(b);const items=[];for(const r of rocks){const p=project({x:r[0],y:0,z:r[1]},b);if(p)items.push({depth:p.depth,type:'rock',p,scale:r[2]});}for(const e of enemies){if(!e.dead||e.state==='death'){const p=project({x:e.x,y:e.jump||0,z:e.z},b);if(p){e.screen=p;items.push({depth:p.depth,type:'sprite',o:e,p});}}}const pp=project({x:player.x,y:player.jump,z:player.z},b);if(pp)items.push({depth:pp.depth,type:'sprite',o:player,p:pp});items.sort((a,z)=>z.depth-a.depth);for(const it of items)it.type==='rock'?drawRock(it.p,it.scale):drawSprite(it.o,it.p,b);drawCombatRing(b);drawParticles(b);}
  function drawGround(){const horizon=H*(.30+camera.pitch*.12),grass=ctx.createLinearGradient(0,horizon,0,H);grass.addColorStop(0,'rgba(81,174,75,.06)');grass.addColorStop(1,'rgba(12,65,43,.38)');ctx.fillStyle=grass;ctx.fillRect(0,horizon,W,H-horizon);}
  function drawCombatRing(b){const e=player.combatTarget;if(!e||e.dead)return;ctx.strokeStyle='#ffe76e99';ctx.lineWidth=2;ctx.beginPath();let started=false;for(let a=0;a<=Math.PI*2+.1;a+=.15){const p=project({x:e.x+Math.cos(a)*2.05,y:.03,z:e.z+Math.sin(a)*2.05},b);if(p){if(!started){ctx.moveTo(p.x,p.y);started=true;}else ctx.lineTo(p.x,p.y);}}ctx.stroke();}
  function drawLine3(a,z,color,b){const p=project(a,b),q=project(z,b);if(!p||!q)return;ctx.strokeStyle=color;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}
  function drawRock(p,s){const w=p.scale*s,h=p.scale*s*1.2;ctx.fillStyle='#0c1c20aa';ctx.beginPath();ctx.ellipse(p.x,p.y,w*.7,w*.2,0,0,7);ctx.fill();const g=ctx.createLinearGradient(p.x,p.y-h,p.x,p.y);g.addColorStop(0,'#718984');g.addColorStop(1,'#243d3a');ctx.fillStyle=g;ctx.beginPath();ctx.moveTo(p.x-w*.55,p.y);ctx.lineTo(p.x-w*.38,p.y-h*.65);ctx.lineTo(p.x,p.y-h);ctx.lineTo(p.x+w*.42,p.y-h*.55);ctx.lineTo(p.x+w*.55,p.y);ctx.closePath();ctx.fill();}
  function drawSprite(o,p,b){const fx=Math.sin(o.face||0),fz=Math.cos(o.face||0),side=fx*b.r.x+fz*b.r.z,depth=fx*b.f.x+fz*b.f.z,useDirectional=o.kind==='slime'&&['idle','move','attack'].includes(o.state);let d=atlasDefs[o.kind],img=atlases[o.kind],row=o.row,frame=0,mirror=false;
    if(useDirectional){d=atlasDefs.directional;img=atlases.directional;const direction=(Math.round(Math.atan2(side,-depth)/(Math.PI/4))+8)%8;row=direction+(o.state==='attack'?8:0);if(o.state==='idle')frame=0;else if(o.state==='move')frame=Math.floor(o.stateT*o.frameRate)%d.cols;else frame=Math.min(d.cols-1,Math.floor(Math.min(.999,o.stateT/Math.max(.001,o.duration))*d.cols));}
    else{const loop=o.state==='idle'||o.state==='move';frame=loop?Math.floor(o.stateT*o.frameRate)%d.cols:Math.min(d.cols-1,Math.floor(Math.min(.999,o.stateT/Math.max(.001,o.duration))*d.cols));row=Math.max(0,Math.min(d.rows-1,row));if(side<-.12)o.mirror=true;else if(side>.12)o.mirror=false;mirror=o.mirror;}
    const sw=img.width/d.cols,sh=img.height/d.rows;let height=o.size*p.scale,width=height*(sw/sh),pulse=o===target?1.05:1;height*=pulse;width*=pulse;ctx.save();ctx.translate(p.x,p.y);if(o===target){ctx.strokeStyle='#ffcf63';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,2,width*.31,height*.09,0,0,7);ctx.stroke();}ctx.shadowColor=o.kind==='slime'?'#34cfff66':'#0008';ctx.shadowBlur=12;if(mirror)ctx.scale(-1,1);ctx.drawImage(img,frame*sw,row*sh,sw,sh,-width/2,-height,width,height);if(mirror)ctx.scale(-1,1);ctx.shadowBlur=0;if(o.kind!=='slime'&&!o.dead){ctx.fillStyle='#071014dd';ctx.fillRect(-width*.3,-height-10,width*.6,5);ctx.fillStyle=o.hp/o.maxHp<.36?'#ffd05e':'#ef5b4d';ctx.fillRect(-width*.3,-height-10,width*.6*(o.hp/o.maxHp),5);}ctx.restore();}
  function drawParticles(b){ctx.save();for(const p of particles){const q=project(p,b);if(!q)continue;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(q.x,q.y,Math.max(1,p.size*q.scale),0,7);ctx.fill();}ctx.restore();}
  function update(dt){if(gameOver){player.stateT+=dt;return;}player.attackCd=Math.max(0,player.attackCd-dt);player.invuln=Math.max(0,player.invuln-dt);player.energy=Math.min(100,player.energy+20*dt);if(player.combatTarget&&(player.combatTarget.dead||player.combatTarget.hp<=0)){player.combatTarget=null;player.queuedAttack=false;}let ix=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),iz=(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0),combat=player.combatTarget;
    if(combat){const dx=combat.x-player.x,dz=combat.z-player.z,l=Math.hypot(dx,dz)||1;player.face=Math.atan2(dx,dz);if(['idle','move'].includes(player.state)){if(l>2.18)movePlayer(dx/l,dz/l,dt);else if(l<1.88)movePlayer(-dx/l,-dz/l,dt);else{player.vx*=Math.exp(-12*dt);player.vz*=Math.exp(-12*dt);if(player.state==='move')setState(player,'idle');if(player.queuedAttack)performAttack(combat);}}}
    else if(ix||iz){const sy=Math.sin(camera.yaw),cy=Math.cos(camera.yaw);const wx=ix*cy+iz*sy,wz=-ix*sy+iz*cy,mag=Math.hypot(wx,wz);movePlayer(wx/mag,wz/mag,dt);player.moveTarget=null;}else if(player.moveTarget&&['idle','move'].includes(player.state)){const dx=player.moveTarget.x-player.x,dz=player.moveTarget.z-player.z,l=Math.hypot(dx,dz);if(l>.25)movePlayer(dx/l,dz/l,dt);else player.moveTarget=null;}else{player.vx*=Math.exp(-9*dt);player.vz*=Math.exp(-9*dt);if(player.state==='move')setState(player,'idle');}
    player.x+=player.vx*dt;player.z+=player.vz*dt;player.x=Math.max(-14,Math.min(14,player.x));player.z=Math.max(-14,Math.min(14,player.z));if(player.jump>0||player.jumpV>0){player.jumpV-=13*dt;player.jump=Math.max(0,player.jump+player.jumpV*dt);if(!player.jump)player.jumpV=0;}advanceState(player,dt);for(const e of enemies)updateEnemy(e,dt);updateParticles(dt);camera.target.x+=(player.x-camera.target.x)*Math.min(1,dt*4);camera.target.z+=(player.z-camera.target.z)*Math.min(1,dt*4);updateUI();}
  function movePlayer(x,z,dt){if(!['idle','move'].includes(player.state))return;const speed=5.2;player.vx+=(x*speed-player.vx)*Math.min(1,dt*8);player.vz+=(z*speed-player.vz)*Math.min(1,dt*8);player.face=Math.atan2(x,z);setState(player,'move');}
  function advanceState(o,dt){o.stateT+=dt;if(o.duration&&o.stateT>=o.duration){if(o.state==='death'){o.dead=true;if(o===player)gameOver=true;return;}o.duration=0;setState(o,'idle');}}
  function updateEnemy(e,dt){if(e.dead)return;advanceState(e,dt);e.attackCd-=dt;if(!['idle','move'].includes(e.state))return;const dx=player.x-e.x,dz=player.z-e.z,l=Math.hypot(dx,dz);if(!e.aggro){setState(e,'idle');return;}if(l<10&&l>2.08){setState(e,'move');const speed=e.kind==='wolf'?2.15:1.7;e.vx=dx/l*speed;e.vz=dz/l*speed;e.face=Math.atan2(e.vx,e.vz);e.x+=e.vx*dt;e.z+=e.vz*dt;}else if(l<=2.08&&e.attackCd<=0){e.face=Math.atan2(dx,dz);timedState(e,'attack',.75);e.attackCd=e.kind==='wolf'?1.8:2.2;setTimeout(()=>{if(e.dead||gameOver)return;if(Math.hypot(player.x-e.x,player.z-e.z)<2.5&&player.invuln<=0){player.hp=Math.max(0,player.hp-(e.kind==='wolf'?9:13));player.invuln=.55;timedState(player,player.hp?'hit':'death',player.hp?.55:1.15);burst(player.x,player.z,'#69dfff',9);if(!player.hp)toast('ZERFLOSSEN','#ff8171');}},330);}else setState(e,'idle');}
  function updateParticles(dt){for(const p of particles){p.life-=dt;p.y+=p.vy*dt;p.x+=p.vx*dt;p.z+=p.vz*dt;p.vy-=3*dt;}particles=particles.filter(p=>p.life>0);}
  function burst(x,z,color,n=12){for(let i=0;i<n;i++){const a=Math.random()*7,s=.5+Math.random()*1.7;particles.push({x,y:.7,z,vx:Math.cos(a)*s,vz:Math.sin(a)*s,vy:.8+Math.random()*2,life:.5+Math.random()*.45,size:.025+Math.random()*.04,color});}}
  function attack(){if(gameOver||player.attackCd>0||player.energy<20)return;const e=target&&!target.dead?target:nearestEnemy();if(!e){toast('KEIN ZIEL','#a7d9e6');return;}target=e;e.aggro=true;player.combatTarget=e;player.queuedAttack=true;player.moveTarget=null;toast('ZIEL-LOCK · DISTANZ 2,0','#ffe47a');}
  function performAttack(e){if(!player.queuedAttack||player.attackCd>0||player.energy<20||e.dead)return;player.queuedAttack=false;const dx=e.x-player.x,dz=e.z-player.z;player.face=Math.atan2(dx,dz);player.energy-=20;player.attackCd=.78;timedState(player,'attack',.78);setTimeout(()=>{if(e.dead)return;e.hp=Math.max(0,e.hp-24);timedState(e,e.hp?'hit':'death',e.hp?.62:1.25);burst(e.x,e.z,e.kind==='wolf'?'#afd7ff':'#ffb05f');toast(e.hp?'24 SCHADEN':'BESIEGT',e.hp?'#fff':'#ffce66');},320);}
  function eat(){if(gameOver)return;const e=target&&!target.dead?target:nearestEnemy();if(!e){toast('KEIN ZIEL','#a7d9e6');return;}const dx=e.x-player.x,dz=e.z-player.z,dist=Math.hypot(dx,dz);if(dist>2.35){player.combatTarget=e;toast('ERST AUF FRESSDISTANZ','#ffd277');return;}if(e.hp/e.maxHp>.35){toast('ERST AUF 35 % SCHWÄCHEN','#ff8a78');return;}player.face=Math.atan2(dx,dz);timedState(player,'eat',1.25);e.state='hit';e.row=3;e.stateT=0;setTimeout(()=>{e.hp=0;timedState(e,'death',1.15);player.combatTarget=null;player.hp=Math.min(player.maxHp,player.hp+22);burst(e.x,e.z,'#70efff',24);toast('VERSCHLUNGEN!','#75f5cf');},720);}
  function nearestEnemy(){let best=null,bd=1e9;for(const e of enemies)if(!e.dead){const d=Math.hypot(e.x-player.x,e.z-player.z);if(d<bd){bd=d;best=e;}}return best;}
  function updateUI(){ui.playerHp.style.width=(player.hp/player.maxHp*100)+'%';ui.playerEnergy.style.width=player.energy+'%';ui.playerState.textContent=player.state.toUpperCase();document.querySelector('#coords').textContent=`POSITION ${player.x.toFixed(1)} / ${player.z.toFixed(1)}`;if(target&&!target.dead){const dist=Math.hypot(target.x-player.x,target.z-player.z);ui.target.classList.remove('hidden');ui.targetName.textContent=target.name;ui.targetHp.style.width=(target.hp/target.maxHp*100)+'%';ui.targetState.textContent=target.state.toUpperCase();ui.targetHint.textContent=target.hp/target.maxHp<=.35?'FRESSBAR – E DRÜCKEN':`${Math.ceil(target.hp)} / ${target.maxHp} HP · DISTANZ ${dist.toFixed(1)}`;}else ui.target.classList.add('hidden');}
  function frame(now){const dt=Math.min(.033,(now-last)/1000);last=now;update(dt);drawWorld(basis());requestAnimationFrame(frame);}
  canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{canvas.focus();pointer.x=e.clientX;pointer.y=e.clientY;if(e.button===2){pointer.drag=true;pointer.lastX=e.clientX;pointer.lastY=e.clientY;canvas.setPointerCapture(e.pointerId);return;}let picked=null,bd=52;for(const en of enemies)if(!en.dead&&en.screen){const d=Math.hypot(e.clientX-en.screen.x,e.clientY-(en.screen.y-en.size*en.screen.scale*.48));if(d<bd){bd=d;picked=en;}}if(picked){target=picked;toast(picked.name.toUpperCase(),'#ffda87');}else{const g=groundFromScreen(e.clientX,e.clientY);if(g){player.combatTarget=null;player.queuedAttack=false;player.moveTarget=g;toast('BEWEGUNGSZIEL','#9eeec7');}target=null;}updateUI();});
  canvas.addEventListener('pointermove',e=>{pointer.x=e.clientX;pointer.y=e.clientY;if(pointer.drag){camera.yaw-=(e.clientX-pointer.lastX)*.006;camera.pitch=Math.max(.1,Math.min(.65,camera.pitch+(e.clientY-pointer.lastY)*.005));pointer.lastX=e.clientX;pointer.lastY=e.clientY;}});canvas.addEventListener('pointerup',e=>{if(e.button===2)pointer.drag=false;});canvas.addEventListener('wheel',e=>{camera.dist=Math.max(8,Math.min(27,camera.dist+e.deltaY*.012));},{passive:true});
  function nudge(code){const map={KeyW:[0,-1],KeyS:[0,1],KeyA:[-1,0],KeyD:[1,0]},v=map[code];if(!v)return;const sy=Math.sin(camera.yaw),cy=Math.cos(camera.yaw),wx=v[0]*cy+v[1]*sy,wz=-v[0]*sy+v[1]*cy;player.moveTarget={x:Math.max(-14,Math.min(14,player.x+wx*1.2)),z:Math.max(-14,Math.min(14,player.z+wz*1.2))};}
  document.addEventListener('keydown',e=>{keys.add(e.code);if(['KeyW','KeyA','KeyS','KeyD','Space'].includes(e.code))e.preventDefault();if(!e.repeat)nudge(e.code);if(e.repeat)return;if(e.code==='Digit1')attack();if(e.code==='KeyE')eat();if(e.code==='Space'&&!player.jump)player.jumpV=5.2;if(e.code==='KeyR')reset();});document.addEventListener('keyup',e=>keys.delete(e.code));addEventListener('blur',()=>keys.clear());addEventListener('resize',resize);document.querySelector('#toggleHelp').onclick=()=>document.querySelector('#help').classList.toggle('hidden');
  resize();reset();load().then(()=>{document.body.classList.add('loaded');requestAnimationFrame(frame);}).catch(err=>{document.querySelector('#loading').textContent='ASSETS KONNTEN NICHT GELADEN WERDEN';console.error(err);});
})();
